require("./indexB.html");
// require('./mapsB.html');
// require('./newsB.html');
require("./poiB.html");
// require('./mapsBSv.html');
// require('./newsBSv.html');
require("./poiBSv.html");
require("./embedEnB.html");
require("./embedSvB.html");
// require('./css/materialize.css');
require("./css/materialdesignicons.css");
require("./css/master.css");
require("./js/master.js");
// require('./js/jquery-3.2.1.min.js');
